=== GrumpyKater/smarthomatic/tools/shc_e2p_editor/packet_metamodel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Packet">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Header">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded">
							<xs:element ref="UIntValue"/>
							<xs:element ref="IntValue"/>
							<xs:element ref="BoolValue"/>
							<xs:element ref="EnumValue"/>
							<xs:element ref="ByteArray"/>
							<xs:element ref="Reserved"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="HeaderExtension" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="MessageType" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>All MessageTypes this HeaderExtension is valid for. Make sure only one HeaderExtension is valid for one MessageType!</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:int"/>
								</xs:simpleType>
							</xs:element>
							<xs:choice maxOccurs="unbounded">
								<xs:element ref="UIntValue"/>
								<xs:element ref="IntValue"/>
								<xs:element ref="BoolValue"/>
								<xs:element ref="EnumValue"/>
								<xs:element ref="ByteArray"/>
								<xs:element ref="Reserved"/>
							</xs:choice>
							<xs:element name="ContainsMessageData" type="xs:boolean"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="MessageGroup" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="Description" type="xs:string"/>
							<xs:element name="MessageGroupID">
								<xs:simpleType>
									<xs:restriction base="xs:unsignedInt">
										<xs:minInclusive value="0"/>
										<xs:maxInclusive value="127"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Message" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Name" type="xs:string"/>
										<xs:element name="Description" type="xs:string"/>
										<xs:element name="MessageID">
											<xs:simpleType>
												<xs:restriction base="xs:unsignedInt">
													<xs:minInclusive value="0"/>
													<xs:maxInclusive value="15"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="MessageType" maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>All MessageTypes this Message is valid for.</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:int"/>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Validity">
											<xs:annotation>
												<xs:documentation>Tells if the message definition is only for testing (and could change in its format definition), is released for production use (and should not be changed anymore) or deprecated (and may be removed some day).</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="test|released|deprecated"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:choice maxOccurs="unbounded">
											<xs:element ref="UIntValue"/>
											<xs:element ref="IntValue"/>
											<xs:element ref="BoolValue"/>
											<xs:element ref="EnumValue"/>
											<xs:element ref="ByteArray"/>
											<xs:element ref="Reserved"/>
										</xs:choice>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="UIntValue">
		<xs:annotation>
			<xs:documentation>An unsigned integer value with 1 to 32 bits in size.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ID" type="xs:string"/>
				<xs:element name="Description"/>
				<xs:element name="Bits">
					<xs:simpleType>
						<xs:restriction base="xs:unsignedInt">
							<xs:minInclusive value="1"/>
							<xs:maxInclusive value="32"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="MinVal" type="xs:unsignedInt"/>
				<xs:element name="MaxVal" type="xs:unsignedInt"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="IntValue">
		<xs:annotation>
			<xs:documentation>A signed integer value with 1 to 32 bits in size.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ID" type="xs:string"/>
				<xs:element name="Description"/>
				<xs:element name="Bits">
					<xs:simpleType>
						<xs:restriction base="xs:unsignedInt">
							<xs:minInclusive value="1"/>
							<xs:maxInclusive value="32"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="MinVal" type="xs:int"/>
				<xs:element name="MaxVal" type="xs:int"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="BoolValue">
		<xs:annotation>
			<xs:documentation>A boolean value, stored as one bit being 0 (false) or 1 (true).</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ID" type="xs:string"/>
				<xs:element name="Description"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="EnumValue">
		<xs:annotation>
			<xs:documentation>An integer value in EEPROM with an additional name describing the meaning.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ID" type="xs:string"/>
				<xs:element name="Description" type="xs:string"/>
				<xs:element name="Bits" type="xs:unsignedInt"/>
				<xs:element name="Element" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Value" type="xs:unsignedInt"/>
							<xs:element name="Name" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ByteArray">
		<xs:annotation>
			<xs:documentation>A series of bytes with a given length.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ID" type="xs:string"/>
				<xs:element name="Description" type="xs:string"/>
				<xs:element name="Bytes">
					<xs:simpleType>
						<xs:restriction base="xs:unsignedInt">
							<xs:minInclusive value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Reserved">
		<xs:annotation>
			<xs:documentation>A series of bits with a given length blocking space for later use.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Bits">
					<xs:simpleType>
						<xs:restriction base="xs:unsignedInt">
							<xs:minInclusive value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== GrumpyKater/smarthomatic/tools/shc_e2p_editor/packet_catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<Packet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="packet_metamodel.xsd">
	<Header>
		<UIntValue>
			<ID>CRC32</ID>
			<Description>CRC32 value of byte 4..n</Description>
			<Bits>32</Bits>
			<MinVal>0</MinVal>
			<MaxVal>4294967295</MaxVal>
		</UIntValue>
		<UIntValue>
			<ID>SenderID</ID>
			<Description>The SenderID is the DeviceID of the sending device. It's only allowed to send packets with the own DeviceID. 0 = base station, others are arbitrary.</Description>
			<Bits>12</Bits>
			<MinVal>0</MinVal>
			<MaxVal>4095</MaxVal>
		</UIntValue>
		<UIntValue>
			<ID>PacketCounter</ID>
			<Description>The PacketCounter is counted up throughout the whole lifetime of the device and is used to make the encrypted packets differently from each other every time. Packets received with the same or lower number must be ignored per SenderID.</Description>
			<Bits>24</Bits>
			<MinVal>0</MinVal>
			<MaxVal>16777215</MaxVal>
		</UIntValue>
		<UIntValue>
			<ID>MessageGroupID</ID>
			<Description/>
			<Bits>4</Bits>
			<MinVal>0</MinVal>
			<MaxVal>15</MaxVal>
		</UIntValue>
		<UIntValue>
			<ID>MessageID</ID>
			<Description>0 = Generic, 1..9 = Reserved, others are arbitrary</Description>
			<Bits>7</Bits>
			<MinVal>0</MinVal>
			<MaxVal>127</MaxVal>
		</UIntValue>
		<EnumValue>
			<ID>MessageType</ID>
			<Description>The message type influences the behaviour with sending the packet. E.g. requests are acknowledged.</Description>
			<Bits>1</Bits>
			<Element>
				<Value>0</Value>
				<Name>Status</Name>
			</Element>
			<Element>
				<Value>1</Value>
				<Name>Request</Name>
			</Element>
		</EnumValue>
	</Header>
	<MessageGroup>
		<Name>Generic</Name>
		<Description>This group contains messages useful for different devices.</Description>
		<MessageGroupID>0</MessageGroupID>
		<Message>
			<Name>GenericAck</Name>
			<Description>Acknowledge about receiving a request from another device.</Description>
			<MessageID>0</MessageID>
			<MessageType>0</MessageType>
			<Validity>test</Validity>
			<UIntValue>
				<ID>SenderID</ID>
				<Description>The SenderID is the DeviceID of the sending device. It's only allowed to send packets with the own DeviceID. 0 = base station, others are arbitrary.</Description>
				<Bits>12</Bits>
				<MinVal>0</MinVal>
				<MaxVal>4095</MaxVal>
			</UIntValue>
			<UIntValue>
				<ID>PacketCounter</ID>
				<Description>The PacketCounter is counted up throughout the whole lifetime of the device and is used to make the encrypted packets differently from each other every time. Packets received with the same or lower number must be ignored per SenderID.</Description>
				<Bits>24</Bits>
				<MinVal>0</MinVal>
				<MaxVal>16777215</MaxVal>
			</UIntValue>
		</Message>
		<Message>
			<Name>BatteryStatus</Name>
			<Description>Tells the current battery status in percent.</Description>
			<MessageID>5</MessageID>
			<MessageType>0</MessageType>
			<Validity>test</Validity>
			<UIntValue>
				<ID>Percentage</ID>
				<Description>The remaining capacity of the battery from 0 (empty) to 100 (full).</Description>
				<Bits>7</Bits>
				<MinVal>0</MinVal>
				<MaxVal>100</MaxVal>
			</UIntValue>
		</Message>
	</MessageGroup>
	<MessageGroup>
		<Name>TempSensor</Name>
		<Description/>
		<MessageGroupID>10</MessageGroupID>
		<Message>
			<Name>TempStatus</Name>
			<Description/>
			<MessageID>1</MessageID>
			<MessageType>0</MessageType>
			<Validity>test</Validity>
			<IntValue>
				<ID>Temperature</ID>
				<Description>temperature [1/100 degree celsius], -50°C = -5000, 50°C = 5000</Description>
				<Bits>16</Bits>
				<MinVal>-32768</MinVal>
				<MaxVal>32767</MaxVal>
			</IntValue>
			<UIntValue>
				<ID>Humidity</ID>
				<Description>relative humidity permill, 0..1000 (other values not defined)</Description>
				<Bits>10</Bits>
				<MinVal>0</MinVal>
				<MaxVal>1000</MaxVal>
			</UIntValue>
			<UIntValue>
				<ID>Brightness</ID>
				<Description>brightness in percent</Description>
				<Bits>7</Bits>
				<MinVal>0</MinVal>
				<MaxVal>100</MaxVal>
			</UIntValue>
		</Message>
	</MessageGroup>
</Packet>

=== GrumpyKater/smarthomatic/tools/shc_e2p_editor/packet_layout.xml
<?xml version="1.0" encoding="UTF-8"?>
<Packet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="packet_metamodel.xsd">
	<Header>
		<UIntValue>
			<ID>CRC32</ID>
			<Description>CRC32 value of byte 4..n</Description>
			<Bits>32</Bits>
			<MinVal>0</MinVal>
			<MaxVal>4294967295</MaxVal>
		</UIntValue>
		<UIntValue>
			<ID>SenderID</ID>
			<Description>The SenderID is the DeviceID of the sending device. It's only allowed to send packets with the own DeviceID. 0 = base station, others are arbitrary.</Description>
			<Bits>12</Bits>
			<MinVal>0</MinVal>
			<MaxVal>4095</MaxVal>
		</UIntValue>
		<UIntValue>
			<ID>PacketCounter</ID>
			<Description>The PacketCounter is counted up throughout the whole lifetime of the device and is used to make the encrypted packets differently from each other every time. Packets received with the same or lower number must be ignored per SenderID.</Description>
			<Bits>24</Bits>
			<MinVal>0</MinVal>
			<MaxVal>16777215</MaxVal>
		</UIntValue>
		<EnumValue>
			<ID>MessageType</ID>
			<Description>The message type influences the behaviour with sending the packet. E.g. requests are acknowledged.</Description>
			<Bits>4</Bits>
			<Element>
				<Value>0</Value>
				<Name>Get</Name>
			</Element>
			<Element>
				<Value>1</Value>
				<Name>Set</Name>
			</Element>
			<Element>
				<Value>2</Value>
				<Name>SetGet</Name>
			</Element>
			<Element>
				<Value>8</Value>
				<Name>Status</Name>
			</Element>
			<Element>
				<Value>9</Value>
				<Name>Ack</Name>
			</Element>
			<Element>
				<Value>10</Value>
				<Name>AckStatus</Name>
			</Element>
		</EnumValue>
	</Header>
	<HeaderExtension>
		<MessageType>0</MessageType>
		<UIntValue>
			<ID>ReceiverID</ID>
			<Description>The ID of the device to process the request. Use 4095 for broadcasts.</Description>
			<Bits>12</Bits>
			<MinVal>0</MinVal>
			<MaxVal>4095</MaxVal>
		</UIntValue>
		<UIntValue>
			<ID>MessageGroupID</ID>
			<Description>0 = Generic, 1..9 = Reserved, others are arbitrary</Description>
			<Bits>7</Bits>
			<MinVal>0</MinVal>
			<MaxVal>127</MaxVal>
		</UIntValue>
		<UIntValue>
			<ID>MessageID</ID>
			<Description/>
			<Bits>4</Bits>
			<MinVal>0</MinVal>
			<MaxVal>15</MaxVal>
		</UIntValue>
		<ContainsMessageData>false</ContainsMessageData>
	</HeaderExtension>
	<HeaderExtension>
		<MessageType>1</MessageType>
		<MessageType>2</MessageType>
		<UIntValue>
			<ID>ReceiverID</ID>
			<Description>The ID of the device to process the request. Use 4095 for broadcasts.</Description>
			<Bits>12</Bits>
			<MinVal>0</MinVal>
			<MaxVal>4095</MaxVal>
		</UIntValue>
		<UIntValue>
			<ID>MessageGroupID</ID>
			<Description>0 = Generic, 1..9 = Reserved, others are arbitrary</Description>
			<Bits>7</Bits>
			<MinVal>0</MinVal>
			<MaxVal>127</MaxVal>
		</UIntValue>
		<UIntValue>
			<ID>MessageID</ID>
			<Description/>
			<Bits>4</Bits>
			<MinVal>0</MinVal>
			<MaxVal>15</MaxVal>
		</UIntValue>
		<ContainsMessageData>true</ContainsMessageData>
	</HeaderExtension>
	<HeaderExtension>
		<MessageType>8</MessageType>
		<UIntValue>
			<ID>MessageGroupID</ID>
			<Description>0 = Generic, 1..9 = Reserved, others are arbitrary</Description>
			<Bits>7</Bits>
			<MinVal>0</MinVal>
			<MaxVal>127</MaxVal>
		</UIntValue>
		<UIntValue>
			<ID>MessageID</ID>
			<Description/>
			<Bits>4</Bits>
			<MinVal>0</MinVal>
			<MaxVal>15</MaxVal>
		</UIntValue>
		<ContainsMessageData>true</ContainsMessageData>
	</HeaderExtension>
	<HeaderExtension>
		<MessageType>9</MessageType>
		<UIntValue>
			<ID>AckSenderID</ID>
			<Description>The ID of the requestor whose request is acknowledged.</Description>
			<Bits>12</Bits>
			<MinVal>0</MinVal>
			<MaxVal>4095</MaxVal>
		</UIntValue>
		<UIntValue>
			<ID>AckPacketCounter</ID>
			<Description>The PacketCounter of the request that is acknowledged.</Description>
			<Bits>24</Bits>
			<MinVal>0</MinVal>
			<MaxVal>16777215</MaxVal>
		</UIntValue>
		<BoolValue>
			<ID>Error</ID>
			<Description>Tells if there was an error fulfilling the request or not.</Description>
		</BoolValue>
		<ContainsMessageData>false</ContainsMessageData>
	</HeaderExtension>
	<HeaderExtension>
		<MessageType>10</MessageType>
		<UIntValue>
			<ID>AckSenderID</ID>
			<Description>The ID of the requestor whose request is acknowledged.</Description>
			<Bits>12</Bits>
			<MinVal>0</MinVal>
			<MaxVal>4095</MaxVal>
		</UIntValue>
		<UIntValue>
			<ID>AckPacketCounter</ID>
			<Description>The PacketCounter of the request that is acknowledged.</Description>
			<Bits>24</Bits>
			<MinVal>0</MinVal>
			<MaxVal>16777215</MaxVal>
		</UIntValue>
		<BoolValue>
			<ID>Error</ID>
			<Description>Tells if there was an error fulfilling the request or not.</Description>
		</BoolValue>
		<UIntValue>
			<ID>MessageGroupID</ID>
			<Description>0 = Generic, 1..9 = Reserved, others are arbitrary</Description>
			<Bits>7</Bits>
			<MinVal>0</MinVal>
			<MaxVal>127</MaxVal>
		</UIntValue>
		<UIntValue>
			<ID>MessageID</ID>
			<Description/>
			<Bits>4</Bits>
			<MinVal>0</MinVal>
			<MaxVal>15</MaxVal>
		</UIntValue>
		<ContainsMessageData>true</ContainsMessageData>
	</HeaderExtension>
	<MessageGroup>
		<Name>Generic</Name>
		<Description>This group contains messages useful for different devices.</Description>
		<MessageGroupID>0</MessageGroupID>
		<Message>
			<Name>BatteryStatus</Name>
			<Description>Tells the current battery status in percent. Please note that the "Get" may not be answered because a device does not listen to requests.</Description>
			<MessageID>5</MessageID>
			<MessageType>0</MessageType>
			<MessageType>8</MessageType>
			<MessageType>10</MessageType>
			<Validity>test</Validity>
			<UIntValue>
				<ID>Percentage</ID>
				<Description>The remaining capacity of the battery from 0 (empty) to 100 (full).</Description>
				<Bits>7</Bits>
				<MinVal>0</MinVal>
				<MaxVal>100</MaxVal>
			</UIntValue>
		</Message>
	</MessageGroup>
	<MessageGroup>
		<Name>TempSensor</Name>
		<Description>This message group contains messages for a device that can measure temperature and humidity as well as a brightness value.</Description>
		<MessageGroupID>10</MessageGroupID>
		<Message>
			<Name>TempHumBriStatus</Name>
			<Description>This is a message containing temperature, humidity and brightness.</Description>
			<MessageID>1</MessageID>
			<MessageType>0</MessageType>
			<MessageType>8</MessageType>
			<MessageType>10</MessageType>
			<Validity>test</Validity>
			<IntValue>
				<ID>Temperature</ID>
				<Description>temperature [1/100 degree celsius], -50°C = -5000, 50°C = 5000</Description>
				<Bits>16</Bits>
				<MinVal>-32768</MinVal>
				<MaxVal>32767</MaxVal>
			</IntValue>
			<UIntValue>
				<ID>Humidity</ID>
				<Description>relative humidity permill, 0..1000 (other values not defined)</Description>
				<Bits>10</Bits>
				<MinVal>0</MinVal>
				<MaxVal>1000</MaxVal>
			</UIntValue>
			<UIntValue>
				<ID>Brightness</ID>
				<Description>brightness in percent</Description>
				<Bits>7</Bits>
				<MinVal>0</MinVal>
				<MaxVal>100</MaxVal>
			</UIntValue>
		</Message>
	</MessageGroup>
	<MessageGroup>
		<Name>PowerSwitch</Name>
		<Description/>
		<MessageGroupID>20</MessageGroupID>
		<Message>
			<Name>SwitchState</Name>
			<Description/>
			<MessageID>1</MessageID>
			<MessageType>0</MessageType>
			<MessageType>1</MessageType>
			<MessageType>2</MessageType>
			<MessageType>8</MessageType>
			<MessageType>9</MessageType>
			<MessageType>10</MessageType>
			<Validity>test</Validity>
			<BoolValue>
				<ID>On</ID>
				<Description/>
			</BoolValue>
			<UIntValue>
				<ID>TimeoutSec</ID>
				<Description>The time after which the switch is automatically toggled again. Use 0 to disable this.</Description>
				<Bits>16</Bits>
				<MinVal>0</MinVal>
				<MaxVal>65535</MaxVal>
			</UIntValue>
		</Message>
	</MessageGroup>
</Packet>
